#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: table
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'source/**/*.s+(a|c)ss'
  ignore:
    - 'source/_normalize.scss'
    - 'source/_framework.scss'
    - 'source/_layout.scss'
# Rule Configuration
rules:
  # Extends
  extends-before-declarations: 1
  placeholder-in-extend: 1
  extends-before-mixins: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  # Disallows
  no-attribute-selectors: 0
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  no-transition-all: 1
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
